Pusher-Labs/thorchain-explorer

src/app/_pipes/asset-units.pipe.spec.ts
src/app/_pipes/asset-units.pipe.ts
src/app/_pipes/pipes.module.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.module.ts

- creates asset unit pipe
- network status numbers formatted

asset unit pipe

---

src/styles.scss

closes #27
- table row hover
- active anchor tags

minor table style changes

---

package.json
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/nodes/nodes.component.html
src/environments/environment.prod.ts
src/environments/environment.ts

- hides stats section
- prod builds on live

Connect backend

---

README.md
src/app/pool/pool-details/pool-details.component.html
src/styles.scss

- divides data into more consumable parts 
- lines up corresponding keys.
closes #66

splits apart individual asset table

---

src/app/_components/volume/volume.component.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

- displays error if dash fails to load
- updates volume chart to just show in UTC

dash loading & volume chart update

---

src/app/_classes/constants-table.ts
src/app/_services/constants.service.ts
src/app/network/constants/constants.component.html
src/app/network/constants/constants.component.spec.ts
src/app/network/constants/constants.component.ts
src/app/network/network-details/network-details.component.ts
src/app/network/network.component.html
src/app/network/network.module.ts

- find inside network tab -> constants

Constants Page

---

src/app/network/constants/constants.component.html
src/app/network/constants/constants.component.ts

- formats asset units for CliTxCost, MinimumBondInRune, and TransactionFee
- Adds (Blocks) to 
Bad Validator Rate
Double Sign Max Age
Fund Migration Interval
Jail Time Keygen
Jail Time Keysign
New Pool Cycle
Observe Flex
Old Validator Rate
Rotate Per Block Height
Rotate Retry Blocks
Signing Transaction Period
Stake Lock Up Blocks
- Adds % to Ygg Fund Limit

formatted constants

---

src/app/_classes/helpers/formattable-asset.ts
src/app/_classes/network-status.ts
src/app/_components/network-summary-table/network-summary-table.component.html
src/app/_components/network-summary-table/network-summary-table.component.ts
src/app/_services/coingecko.service.spec.ts
src/app/_services/coingecko.service.ts
src/app/_services/network.service.ts
src/app/app.module.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/network/network-details/network-details.component.html
src/app/network/network-details/network-details.component.ts

- adds total bonded
- total total capital
- updates value for staked capital

updates metrics, adds usd price

---

src/app/_classes/thor-node.ts
src/app/_services/last-block.service.spec.ts
src/app/_services/last-block.service.ts
src/app/app.module.ts
src/app/node/node.component.ts
src/app/nodes/nodes.component.ts

- last block service
- checks node jail release height against last block to see if node is in jail

Nodes table jailed status

---

src/app/node/node.component.ts

fix jail issue

---

src/app/_classes/network-status.ts
src/app/_components/network-summary-table/network-summary-table.component.html

separates total bonds into active/standby on network summary table

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

fixes error handling on dash

---

src/app/app.component.scss
src/app/network/constants/constants.component.html
src/app/network/constants/constants.component.ts
src/app/network/network-details/network-details.component.html
src/app/network/network-details/network-details.component.ts
src/app/network/network.module.ts
src/app/pools/pools.component.html
src/app/pools/pools.component.ts
src/app/pools/pools.module.ts
src/app/stakers/stakers.component.html
src/app/transactions/transactions.component.html
src/app/transactions/transactions.component.ts
src/app/transactions/transactions.module.ts

UI error handling across root paths

---

src/app/_components/nodes-table/nodes-table.component.html
src/app/_components/nodes-table/nodes-table.component.ts
src/app/nodes/nodes.component.html
src/app/nodes/nodes.component.ts
src/app/nodes/nodes.module.ts

separates node tables

---

src/app/_classes/thor-node.ts
src/app/nodes/nodes.component.ts

add ready nodes in standby table

---

src/app/_classes/network-status.ts
src/app/network/network-details/network-details.component.html
src/app/network/network-details/network-details.component.ts

adds usd values to network page block rewards and bond metrics
closes #137

Network usd stats

---

src/app/_classes/global-stats.ts
src/app/_components/stats-table/stats-table.component.html
src/app/_components/stats-table/stats-table.component.spec.ts
src/app/_components/stats-table/stats-table.component.ts
src/app/_services/stats.service.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

adds usd values to the global stats section on dashboard
closes #115

Usd dashboard stats

---

src/app/_components/pool-stakers-table/pool-stakers-table.component.html
src/app/_components/pool-stakers-table/pool-stakers-table.component.scss
src/app/_components/pool-stakers-table/pool-stakers-table.component.spec.ts
src/app/_components/pool-stakers-table/pool-stakers-table.component.ts
src/app/_components/pool-stakers-table/pool-stakers-table.module.ts
src/styles.scss

Pools -> Staker Ownership Pie Chart

---

src/app/_classes/network-status.ts
src/app/_services/thorchain-network.service.ts

network status - checks bond exists before mapping

---

src/app/transaction/transaction.component.html

Include stake units amount in stake transaction page

---

src/app/pools/pools.component.html

fix extra long logo

---

src/app/nodes/nodes.component.ts

sort standby nodes by bond

---

src/app/_components/map/map.component.ts

Fixing various map issues discussed on chat.

Fix hover, Add city node count etc.

---

src/app/_components/map/map.component.ts

fix hover color

---

src/app/_components/search/search.component.ts
src/app/transaction/transaction.component.html

check for bnb address in search

---

src/app/_services/pool.service.ts
src/app/pool/pool-details/pool-details.component.html

add earned fields

---

src/index.html

Clarify is network explorer instead of block explorer

Change to "Network Explorer"

---

src/app/_classes/asset.ts

matches logo for btc.btc

---

src/app/_components/nodes-table/nodes-table.component.html
src/app/_components/nodes-table/nodes-table.component.scss

bugfix for pinned node display
